name: Build and Deploy Resume

on:
  push:
   branches:
     - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: fowles-resume.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Save pdf file
        uses: actions/upload-artifact@master
        with:
          name: resume
          path: fowles-resume.pdf
  deploy_pdf:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Get gh pages repo
        uses: actions/checkout@master
        with:
          repository: afowles/afowles.github.io
          token: ${{secrets.ACCESS_TOKEN}}
      - name: Pull saved pdf
        uses: actions/download-artifact@master
        with:
          name: resume
      - name: Commit file
        run: |
           git config --local user.email "action.github.com"
           git config --local user.name "GitHub Action"
           git add fowles-resume.pdf
           git commit -m "Pushed by GitHub Action" -a
           git push origin master
